INSERT INTO dbo.Risorsa (ID, Cognome, Nome, Username, Email, FlagPrenotazione)
VALUES (0,'Rimoldi', 'Linda', 'rimolli1', 'linda.rimoldi@reti.it', 1)
INSERT INTO dbo.Risorsa (ID, Cognome, Nome, Username, Email, FlagPrenotazione)
VALUES (0,'Rossi', 'Mario', 'rossima1', 'mario.rossi@reti.it', 1)
INSERT INTO dbo.Risorsa (ID, Cognome, Nome, Username, Email, FlagPrenotazione)
VALUES (0,'Bianchi', 'Francesco', 'biancfr1', 'francesco.bianchi@reti.it', 0)
INSERT INTO dbo.Risorsa (ID, Cognome, Nome, Username, Email, FlagPrenotazione)
VALUES (0,'Galli', 'Marco', 'gallima1', 'marco.galli@reti.it', 0)

INSERT INTO dbo.Edificio (Nome, Indirizzo, Stato)
VALUES ('Edificio 1', 'Via Verdi 3', 'Disponibile')
INSERT INTO dbo.Edificio (Nome, Indirizzo, Stato)
VALUES ('Edificio 2', 'Via Rossi 4', 'Disponibile')
INSERT INTO dbo.Edificio (Nome, Indirizzo, Stato)
VALUES ('Edificio 6', 'Via Garibaldi 12', 'Non disponibile')

INSERT INTO dbo.Sala (ID_Edificio, Nome, NumeroPostiDisponibili, Stato)
VALUES (1, 'Multifunzionale', 1, 'Prenotabile')
INSERT INTO dbo.Sala (ID_Edificio, Nome, NumeroPostiDisponibili, Stato)
VALUES (2, 'Sala 1', 1, 'Prenotabile')
INSERT INTO dbo.Sala (ID_Edificio, Nome, NumeroPostiDisponibili, Stato)
VALUES (3, 'Sala 2', 2, 'Non prenotabile')

INSERT INTO dbo.Prenotazione (ID_Risorsa, ID_Sala, Descrizione, DataInizioPrenotazione, DataFinePrenotazione)
VALUES (1, 1, 'La prenotazione più bella del mondo!!', '2019-01-12 13:30', '2019-01-12 18:00')
INSERT INTO dbo.Prenotazione (ID_Risorsa, ID_Sala, Descrizione, DataInizioPrenotazione, DataFinePrenotazione)
VALUES (3, 1, 'Riunione giornaliera', '2019-01-10 10:30', '2019-01-10 13:00')
INSERT INTO dbo.Prenotazione (ID_Risorsa, ID_Sala, Descrizione, DataInizioPrenotazione, DataFinePrenotazione)
VALUES (4, 2, 'Riunione', '2019-01-02 13:30', '2019-01-03 18:00')