//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookIt.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BookItEntities : DbContext
    {
        public BookItEntities()
            : base("name=BookItEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Edificio> Edificios { get; set; }
        public virtual DbSet<Prenotazione> Prenotaziones { get; set; }
        public virtual DbSet<Risorsa> Risorsas { get; set; }
        public virtual DbSet<Sala> Salas { get; set; }
    }
}
