//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookIt.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sala
    {
        public int ID_Sala { get; set; }
        public int ID_Edificio { get; set; }
        public string Nome { get; set; }
        public int NumeroPostiDisponibili { get; set; }
        public string Stato { get; set; }
    
        public virtual Edificio Edificio { get; set; }
    }
}
